language: go

sudo: false

go:
    - 1.9.x
    - tip

matrix:
    allow_failures:
        - go: tip

branches:
    only:
        - master

before_install:
    - mkdir -p $HOME/bin
    - curl -sL https://get.binhq.io/binbrew | DEST=$HOME/bin NAME=bin bash
    - bin get golang/dep@0.3.2 $HOME/bin

install: make setup

script: make check ARGS="-v"

after_success: >
    if [[ "$TRAVIS_TAG" && $TRAVIS_GO_VERSION =~ ^1\.9(\.[0-9]+)?$ ]]; then
        bin get goreleaser/goreleaser@0.35.4 $HOME/bin
        goreleaser
    fi
