language: go

sudo: false

go:
    - 1.9.x
    - tip

matrix:
    allow_failures:
        - go: tip

before_install:
    - mkdir -p $HOME/bin
    - curl -sL http://get.binhq.io/gitbin | DEST=$HOME/bin bash
    - gitbin get golang/dep 0.3.2 -o $HOME/bin

install: make setup

script: make check ARGS="-v"

after_success: >
    if [[ "$TRAVIS_TAG" && $TRAVIS_GO_VERSION =~ ^1\.9(\.[0-9]+)?$ ]]; then
        gitbin get goreleaser/goreleaser 0.35.4 -o $HOME/bin
        goreleaser
    fi
