language: go

sudo: false

go:
    - 1.9.x
    - tip

matrix:
    allow_failures:
        - go: tip

before_install:
    - mkdir -p $HOME/bin
    - curl -sL http://get.binhq.io/gitbin | DEST=$HOME/bin bash
    - gitbin get golang/dep 0.3.2 -o $HOME/bin

install: dep ensure

script: go test ./...
